[pyprland]
plugins = ["scratchpads", "magnify"]

[scratchpads.spoti]
command = "spotify"
animation = "fromTop"
unfocus = "hide"

[scratchpads.kittyy]
command = "kitty --class scratchpad -e ranger"
class = "scratchpad"

