[pyprland]
plugins = ["scratchpads", "magnify"]

[scratchpads.spoti]
command = "spotify"
animation = "fromRight"
unfocus = "hide"
# animation = "fromBottom"
# margin = 50
# size = "50% 50%"
# class = "spotiScratch"

[scratchpads.kittyy]
command = "kitty --class scratchpad -e ranger"
# unfocus = "hide"
class = "scratchpad"

