[pyprland]
plugins = ["scratchpads", "magnify"]

[scratchpads.spoti]
command = "spotify"
unfocus = "hide"
animation = "fromTop"
position = "25% 40%"


[scratchpads.ferdi]
command = "ferdium"
animation = "fromBottom"


# Not Positioning well
# [scratchpads.kittyy]
# command = "kitty --class scratchpad -e ranger"
# margin = 50
# position = "0% 0%"
# size = "85% 85%"
# class = "scratchpad"

