[pyprland]
plugins = ["scratchpads", "magnify"]

[scratchpads.spoti]
command = "spotify --class spotiScratch"
unfocus = "hide"
animation = "fromBottom"
margin = 50
size = "50% 50%"
class = "spotiScratch"

[scratchpads.kittyy]
command = "kitty --class scratchpad -e ranger"
unfocus = "hide"
animation = "fromTop"
position = "0% 50%"
size = "50% 50%"
class = "scratchpad"

