[pyprland]
plugins = ["scratchpads", "magnify"]

[scratchpads.spoti]
command = "spotify"
animation = "fromTop"
unfocus = "hide"

[scratchpads.ferdi]
command = "ferdium --class ferdium"
unfocus = "hide"
animation = "fromBottom"

# Not Positioning well
# [scratchpads.kittyy]
# command = "kitty --class scratchpad -e ranger"
# margin = 50
# position = "0% 0%"
# size = "85% 85%"
# class = "scratchpad"

